#------------------------定义es服务-------------------------
apiVersion: v1
kind: Service
metadata:
  name: es-in
  labels:
    k8s-app: es
spec:
  selector:
    k8s-app: es
  clusterIP: None
  ports:
  - name: es-in
    port: 9300
    protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    k8s-app: es
spec:
  selector:
    k8s-app: es
  ports:
  - name: es-out
    port: 9200
    protocol: TCP
---

# ------------------------定义es的部署 -----------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: es
data:
  elasticsearch.yml: |
    cluster.name: "${NAMESPACE}"
    node.name: "${POD_NAME}"
    network.host: 0.0.0.0
    discovery.seed_hosts: "es-in" 
    cluster.initial_master_nodes: "es-0,es-1,es-2"
---

# ------------------------定义es的部署 -----------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  labels:
    k8s-app: es
spec:
  replicas: 3
  serviceName: es
  selector:
    matchLabels:
      k8s-app: es
  template:
    metadata:
      labels:
        k8s-app: es
    spec:
      containers:
      - name: es
        image: elasticsearch:7.10.1
        imagePullPolicy: IfNotPresent
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        # 应用的内部端口
        ports:
        - containerPort: 9200
          name: es9200
        - containerPort: 9300
          name: es9300
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: '0.1'
            memory: 1Gi
        volumeMounts:
        - name: es-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
      - name: es-config
        configMap:
          name: es