
# ------------------------定义magento的部署 -----------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: magento
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: magento
    spec:
      dnsPolicy: ClusterFirst
      containers:
      # 应用的镜像
      - image: bitnami/magento:2.4.3
        name: magento
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "0.1"
            memory: "1024Mi"
        imagePullPolicy: IfNotPresent
        env:
        - name: MAGENTO_ELASTICSEARCH_HOST
          value: "es"
        - name: MAGENTO_DATABASE_HOST
          value: "mysql"
        - name: MAGENTO_DATABASE_NAME
          value: "bitnami_magento"
        - name: MAGENTO_DATABASE_USER
          value: "cwb"
        - name: MAGENTO_DATABASE_PASSWORD
          value: "Oracle@123"
        - name: MAGENTO_HOST
          value: "magento.oracle-work.com"
        # 应用的内部端口
        ports:
        - containerPort: 8080
          name: magento8080
        - containerPort: 8443
          name: magento8443
        volumeMounts:
        - name: magento-persistent-data
          mountPath: /bitnami/magento
          subPath: magentoData
      volumes:
      # 使用共享存储
      - name: magento-persistent-data
        persistentVolumeClaim:
          claimName: pvc-wilbur