#------------------------定义magento服务-------------------------
apiVersion: v1
kind: Service
metadata:
  name: magento
spec:
  type: LoadBalancer
  ports:
   - port: 80
     targetPort: 8080
     name: magento-80
   - port: 443
     targetPort: 8443
     name: magento-443
  selector:
    app: magento
---

