#------------------------定义mysql服务-------------------------
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
   - port: 3306
     targetPort: 3306
  selector:
    app: mysql
---

# ------------------------定义mysql的部署 -----------------------

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      dnsPolicy: ClusterFirst
      containers:
      # 应用的镜像
      - image: mysql
        name: mysql
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "Oracle@123"
        # 应用的内部端口
        ports:
        - containerPort: 3306
          name: mysql3306
