#------------------------定义mq服务-------------------------
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: rabbitmq-amqpamqp
      port: 5672
    - name: rabbitmq-http
      port: 15672
  selector:
    app: rabbitmq
---
# ------------------------定义rabbitmq的部署 -----------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      dnsPolicy: ClusterFirst
      containers:
      # 应用的镜像
      - image: rabbitmq
        name: rabbitmq
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "0.1"
            memory: "1024Mi"
        imagePullPolicy: IfNotPresent
        env:
        - name: discovery.type
          value: "single-node"
        # 应用的内部端口
        ports:
        - name: rabbitmq-http
          protocol: TCP
          containerPort: 15672
---